# This is not yet fully functional
services:
  db:
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: yes
      MARIADB_DATABASE: pandas3
      MARIADB_USER: pandas3
      MARIADB_PASSWORD: pandas3

  ui:
    build:
      dockerfile: ui/Dockerfile
    volumes:
      - data:/data
    environment:
      PANDAS_DB_URL: jdbc:mariadb://db:3306/pandas3
    ports:
      - "8082:8082"
    depends_on:
      - db

  gatherer:
    build:
      dockerfile: gatherer/Dockerfile
    volumes:
      - data:/data
    environment:
      PANDAS_DB_URL: jdbc:mariadb://db:3306/pandas3
      HERITRIX_URL: http://heritrix:8443
    ports:
      - "8083:8083"
    depends_on:
      - db

volumes:
  db:
    driver: local
  data:
    driver: local