create table INSTANCE_THUMBNAIL
(
    INSTANCE_ID NUMBER NOT NULL,
    DATA BLOB NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    LAST_MODIFIED_DATE TIMESTAMP NOT NULL,
    CONTENT_TYPE VARCHAR2(255) NOT NULL,
    STATUS NUMBER NOT NULL,
    constraint INSTANCE_THUMBNAIL_PK primary key (INSTANCE_ID),
    constraint INSTANCE_ID_FK foreign key (INSTANCE_ID) references INSTANCE(INSTANCE_ID) on delete cascade
);