alter table COL
    add (START_DATE TIMESTAMP,
         END_DATE TIMESTAMP,
         CREATED_DATE TIMESTAMP,
         CREATED_BY NUMBER,
         LAST_MODIFIED_DATE TIMESTAMP,
         LAST_MODIFIED_BY NUMBER);