CREATE SEQUENCE "EMAIL_TEMPLATE_SEQ";

CREATE TABLE "EMAIL_TEMPLATE" 
   (
    "EMAIL_TEMPLATE_ID" NUMBER NOT NULL,
	"AGENCY_ID" NUMBER NOT NULL,
    "NAME" VARCHAR2(256) NOT NULL,
	"TEMPLATE" CLOB
   ) ;
   
ALTER TABLE "EMAIL_TEMPLATE" ADD PRIMARY KEY ("EMAIL_TEMPLATE_ID");
 

