alter table EMAIL_TEMPLATE add CONTACT_TYPE_ID NUMBER ;
comment on column EMAIL_TEMPLATE.CONTACT_TYPE_ID is 'The contact event type to create when using this template';
ALTER TABLE "EMAIL_TEMPLATE" ADD CONSTRAINT "EMAIL_TEMPLATE_CONTACT_TYPE_FK" FOREIGN KEY ("CONTACT_TYPE_ID")
      REFERENCES "CONTACT_TYPE" ("CONTACT_TYPE_ID") DEFERRABLE INITIALLY DEFERRED;