CREATE TABLE INSTANCE_SEED
(
    ID          NUMBER NOT NULL,
    INSTANCE_ID NUMBER NOT NULL,
    URL         VARCHAR2(1024) NOT NULL,
    STATUS      NUMBER,
    REDIRECT    VARCHAR2(1024),
    CONSTRAINT INSTANCE_SEED_PK PRIMARY KEY (ID),
    CONSTRAINT INSTANCE_SEED_INSTANCE_ID_FK FOREIGN KEY (INSTANCE_ID) REFERENCES INSTANCE (INSTANCE_ID) ON DELETE CASCADE
);

CREATE SEQUENCE INSTANCE_SEED_SEQ;