CREATE SEQUENCE REJECTED_DOMAIN_SEQ;

create table REJECTED_DOMAIN (
    ID NUMBER NOT NULL,
    DOMAIN VARCHAR2(255) NOT NULL,
    REASON_ID NUMBER NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    USER_ID NUMBER NOT NULL,
    AGENCY_ID NUMBER,

    CONSTRAINT REJECTED_DOMAIN_PK PRIMARY KEY (ID),
    CONSTRAINT REJECTED_DOMAIN_REASON_FK FOREIGN KEY (REASON_ID) REFERENCES REASON (REASON_ID),
    CONSTRAINT REJECTED_DOMAIN_USER_FK FOREIGN KEY (USER_ID) REFERENCES "INDIVIDUAL" ("INDIVIDUAL_ID"),
    CONSTRAINT REJECTED_DOMAIN_AGENCY_FK FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY (AGENCY_ID)
);

create unique index REJECTED_DOMAIN_AG_DOM_IDX on REJECTED_DOMAIN (AGENCY_ID, DOMAIN);