ALTER TABLE AGENCY
    ADD (
        TRANSFER_CONTACT_ID NUMBER,
        CONSTRAINT FK_AGENCY_TRANSFER_CONTACT
            FOREIGN KEY (TRANSFER_CONTACT_ID)
                REFERENCES INDIVIDUAL (INDIVIDUAL_ID)
                    ON DELETE SET NULL
        );