CREATE TABLE GATHER_INDICATOR
(
    ID              NUMBER NOT NULL,
    INSTANCE_ID     NUMBER NOT NULL,
    INDICATOR_VALUE NUMERIC(4,3) NOT NULL,
    INDICATOR       VARCHAR(64) NOT NULL,
    CONSTRAINT      GATHER_INDICATOR_PK PRIMARY KEY (ID),
    CONSTRAINT      GATHER_INDICATOR_INSTANCE_ID_FK FOREIGN KEY (INSTANCE_ID) REFERENCES INS_GATHER (INSTANCE_ID) ON DELETE CASCADE
);

CREATE SEQUENCE GATHER_INDICATOR_SEQ;
