ALTER TABLE INSTANCE ADD (GATHER_COMMAND_TMP CLOB);
UPDATE INSTANCE SET GATHER_COMMAND_TMP = GATHER_COMMAND;
ALTER TABLE INSTANCE DROP COLUMN GATHER_COMMAND;
ALTER TABLE INSTANCE RENAME COLUMN GATHER_COMMAND_TMP TO GATHER_COMMAND;

ALTER TABLE TITLE_GATHER ADD (GATHER_COMMAND_TMP CLOB);
UPDATE TITLE_GATHER SET GATHER_COMMAND_TMP = GATHER_COMMAND;
ALTER TABLE TITLE_GATHER DROP COLUMN GATHER_COMMAND;
ALTER TABLE TITLE_GATHER RENAME COLUMN GATHER_COMMAND_TMP TO GATHER_COMMAND;

ALTER TABLE PANDAS_EXCEPTION_LOG ADD (EXCEPTION_DETAIL_TMP CLOB);
UPDATE PANDAS_EXCEPTION_LOG SET EXCEPTION_DETAIL_TMP = EXCEPTION_DETAIL;
ALTER TABLE PANDAS_EXCEPTION_LOG DROP COLUMN EXCEPTION_DETAIL;
ALTER TABLE PANDAS_EXCEPTION_LOG RENAME COLUMN EXCEPTION_DETAIL_TMP TO EXCEPTION_DETAIL;