FROM container-registry.prod.nla.gov.au/redhat/ubi9/openjdk-25-runtime
COPY target/pandas4-delivery.jar pandas4-delivery.jar
ENTRYPOINT ["bash", "-c", "exec java ${JAVA_OPTS} -jar pandas4-delivery.jar"]