---

# Deploy pywb 2.9.1 on python 3.11 to /opt/webrecorder.
# Additional config required:
# - edit secret in /opt/webrecorder/etc/oauth2-proxy.cfg
# - start webrecorder-pywb.service / webrecorder-oath2-proxy.service units

- hosts: all
  become: yes
  become_method: sudo

  vars:
    proxy_env:
      http_proxy: "{{ http_proxy }}"
      https_proxy: "{{ https_proxy }}"

  tasks:
    - name: Install 'Development Tools' package group
      yum:
        name: "@Development Tools"
        state: present

    - name: Create a virtualenv for webrecorder
      shell:
        cmd: |
          python3.11 -m venv /opt/webrecorder
          /opt/webrecorder/bin/pip3.11 install --upgrade pip
        creates: /opt/webrecorder

    - name: Install pywb and uwsgi using pip inside the virtualenv
      shell:
        cmd: |
          /opt/webrecorder/bin/pip3.11 install pywb==2.9.1 uwsgi
      environment: "{{ proxy_env }}"

    - name: Ensure wr collections dir exists
      file:
        path: /opt/webrecorder/pywb/collections/wr
        state: directory

    - name: Create archive symlink
      file:
        dest: /opt/webrecorder/pywb/collections/wr/archive
        src: /heritrix/webrecorder/warcs
        force: yes
        state: link

    # oauth2-proxy

    - name: Install oauth2-proxy
      shell: "curl -sL https://github.com/oauth2-proxy/oauth2-proxy/releases/download/v7.5.0/oauth2-proxy-v7.5.0.linux-amd64.tar.gz | tar -zxv -C /opt/webrecorder/bin --strip-components 1"
      environment: "{{ proxy_env }}"

    - name: Generate oauth2-proxy secret
      shell: "dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 | tr -d -- '\n' | tr -- '+/' '-_'"
      register: cookie_secret

    - name: Ensure etc dir exists before copying secret
      file:
        path: /opt/webrecorder/etc
        state: directory

    - name: Copy oauth2-proxy config file with secret
      template:
        src: oauth2-proxy.cfg
        dest: /opt/webrecorder/etc/oauth2-proxy.cfg
      vars:
        cookieSecret: "{{ cookie_secret.stdout }}"

    # Customisation

    - name: Copy pywb configuration files
      copy:
          src: pywb/
          dest: /opt/webrecorder/pywb/

    # fapolicyd

    - name: Install fapolicyd policy for webrecorder
      copy:
        dest: /etc/fapolicyd/rules.d/09-webrecorder.rules
        content: |
          allow perm=any uid=39494 : dir=/opt/webrecorder
          allow perm=any uid=0 : dir=/opt/webrecorder
      register: fapolicyd

    - name: Restart fapolicyd service
      service:
        name: fapolicyd
        state: restarted
      when: fapolicyd.changed

    # pywb and oauth2-proxy systemd

    - name: Install webrecorder-pywb systemd service
      copy:
        src: systemd/webrecorder-pywb.service
        dest: /etc/systemd/system/webrecorder-pywb.service
      register: webrecorder_pywb

    - name: Install webrecorder-oauth2-proxy systemd service
      copy:
        src: systemd/webrecorder-oauth2-proxy.service
        dest: /etc/systemd/system/webrecorder-oauth2-proxy.service
      register: webrecorder_oauth2_proxy

    - name: Reload systemd daemon
      systemd:
          daemon_reload: yes
      when: webrecorder_pywb.changed or webrecorder_oauth2_proxy.changed

    - name: Enable webrecorder-pywb systemd service
      systemd:
          name: webrecorder-pywb
          enabled: yes

    - name: Enable webrecorder-oauth2-proxy systemd service
      systemd:
          name: webrecorder-oauth2-proxy
          enabled: yes

